[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_ANALYTICS_ID = "analytics_id"
  NEXT_PUBLIC_SITE_URL = "https://thoughtkeeper.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs" 